[versions]
alsakt = "0.1.4.3"
core-ktx = "1.10.1"
jna = "5.12.1"
jnaerator-runtime = "0.12"
junit = "4.13.2"
kotlin-test-junit = "1.9.0"
kotlinx-coroutines-core = "1.7.0"
kotlinx-datetime = "0.4.0"
ktor-io = "2.3.0"
metalava-gradle = "0.2.3"
rtmidi-jna = "0.1.3"

[libraries]
alsakt = { module = "dev.atsushieno:alsakt", version.ref = "alsakt" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jnaerator-runtime = { module = "com.nativelibs4java:jnaerator-runtime", version.ref = "jnaerator-runtime" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-test-junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor-io" }
metalava-gradle = { module = "me.tylerbwong.gradle:metalava-gradle", version.ref = "metalava-gradle" }
rtmidi-jna = { module = "dev.atsushieno:rtmidi-jna", version.ref = "rtmidi-jna" }

[plugins]

[bundles]

